name: AnisTrade

on:
  workflow_dispatch: # Permet toujours le déclenchement manuel depuis l'interface GitHub
  schedule:
    # S'exécute à 14:00 UTC (soit 16h00 heure de Paris), du lundi au vendredi
    # Wall Street ouvre à 15h30 (heure de Paris), cela laisse 30 minutes au marché pour générer du volume
    - cron: '0 14 * * 1-5'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run AnisTrade Bot
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -u bot.py
